### ISSUE TITLE
error: identifier "continous_similarity_" is undefined

### ISSUE THREAD

**Issue by lichuanxiang** [thuml/DPH#1]
Hi, when I compile the DPH model following the caffe instructions, there are two errors occurred in line 224 and 349, respectively, which are shown as follows:

src/caffe/layers/pairwise_loss_layer.cu(224): error: identifier "continous_similarity_" is undefined
src/caffe/layers/pairwise_loss_layer.cu(349): error: identifier "continous_similarity_" is undefined

2 errors detected in the compilation of "/tmp/tmpxft_00012396_00000000-19_pairwise_loss_layer.compute_52.cpp1.ii".
make: *** [.build_release/cuda/src/caffe/layers/pairwise_loss_layer.o] Error 1

**Comment by lrhan** [comment]
I also encountered this problem. Have you solved it?

**Comment by caozhangjie** [comment]
I'm sorry for my late reply. @lichuanxiang I have fixed the bug now.

**Comment by hbellafkir** [comment]
still getting the same error
